#!/bin/bash
while :
do
	uptime
	free -h
	echo "redis ESTABLISHED: " `netstat -a | fgrep 6379 | fgrep ESTABLISHED | wc -l`
	echo "redis TIME_WAIT: " `netstat -a | fgrep 6379 | fgrep TIME_WAIT | wc -l`
	sleep 5
done
